### ISSUE TITLE
Support free variables in quasicodes

### ISSUE THREAD

**Issue by christophkoch** [epfldata/squid#23]
This doesn't work (but should (?))

```
ir{($$x: Int)}
```

The error message is "not found: value $$x"

**Comment by LPTK** [comment]
Because Scala has to type-check a block of code before giving it to the quasicode macro, quasicodes have some restrictions compared to QQ. So currently FVs work in QC but they have a more complicated syntax: `ir{$$[Int]('x) + 1}` is equivalent to `ir"($$x:Int)+1"`.

Note that the syntax of FVs is changing anyways; we might have a better option for QC; see this issue: https://github.com/epfldata/squid/issues/10#issuecomment-331394017
