### ISSUE TITLE
Compositionality of .compile

### ISSUE THREAD

**Issue by christophkoch** [epfldata/squid#24]
It would be nice if this worked,
```
> (ir"(x: Int) => x".compile)(2)
error: type mismatch;
 found   : Int(2)
 required: <:<[AnyRef,Any]
       (ir"(x: Int) => x".compile)(2)
                                   ^
```

just like this:
```
> ((x: Int) => x)(2)
res0: Int = 2
```

**Comment by LPTK** [comment]
Unfortunately, this is due to `compile` requiring an implicit evidence that the term is closed. It's a Scala-specific thing that we can't do much about. Possible workarounds are:

```scala
> ir"(x: Int) => x".compile apply 2
res1: Int = 2

> ir"(x: Int) => x".compile(implicitly)(2)
res2: Int = 2

> val pgrm = ir"(x: Int) => x".compile; pgrm(2)
pgrm: Int => Int = <function1>
res5_1: Int = 2
```

Maybe in the future the `Code[T]` data type will have its own `unsafeCompile` method that will not require any implicit, allowing for syntax `q.unsafeCompile(2)`?
