### ISSUE TITLE
Path-dependent types turn into type projections

### ISSUE THREAD

**Issue by ggevay** [epfldata/squid#57]
I'm still struggling with getting `TypeTag` to work. Now the problem is that it is path-dependent on the `universe`.

Simplified example: Let's say that I have these types:
```
class Outer {
  class Inner
}
```
Then
```
  println(dbg_code"""
              val x = new Outer
              val y: x.Inner = ???""")
```
prints
```
code"""{
  val x_0 = new test.Outer();
  val y_1 = ((scala.Predef.???): (test.Outer)#Inner);
  ()
}"""
```
where `x.inner` turned into `Outer#Inner`.

This is a problem in Emma, because after some code fragment runs through Squid, I'm getting errors such as
```
found   : scala.reflect.api.JavaUniverse#TypeTag[String]
 required: reflect.runtime.universe.TypeTag[String]
```

**Comment by LPTK** [comment]
Sorry, I should have pointed you to [this Squid feature list](https://github.com/epfldata/squid/blob/master/doc/reference/Quasiquotes.md#supported-scala-features) from the start. There is expressly no support for path-dependent types in Squid.

I am wondering why you need to embed type tags in the DSL code fragments, though. What is the use case?

**Comment by LPTK** [comment]
Ugh... that's a bit annoying.

Note that `ClassTag` should be problematic. As for `TypeTag`, it's actually problematic because `scala.reflect.runtime.universe` is not a module but a simple `val`, defined as:

```scala
lazy val universe: api.JavaUniverse = new runtime.JavaUniverse
```

One workaround would be to define your own module universe as:

```scala
object universe extends runtime.JavaUniverse
```
...though that would not help if you want to use definitions you can't change such as the Spark ones.
Maybe then, it would be sufficient to declare an implicit conversion from `scala.reflect.api.JavaUniverse#TypeTag[T]` to `reflect.runtime.universe.TypeTag[T]`, implemented as a cast?

**Comment by LPTK** [comment]
I made a typo in the message above: class tags are **not** problematic; they embed well. For example:

```scala
scala> import squid.TestDSL.Predef._
import squid.TestDSL.Predef._

scala> code"scala.reflect.classTag[String]"
res0: squid.TestDSL.ClosedCode[scala.reflect.ClassTag[String]] = code"scala.reflect.`package`.classTag[java.lang.String](scala.reflect.ClassTag.apply[java.lang.String](_root_.scala.Predef.classOf[String]))"
```
