### ISSUE TITLE
The context is inferred `Any` sometimes instead of `AnyRef`

### ISSUE THREAD

**Issue by amirsh** [epfldata/squid#7]
You can see this issue in the following code (extracted from DBLAB):
```scala
List(1, 2, 3).foldLeft(ir"0") { (acc, exp) =>
  ir"if($acc != 0) $acc else $exp"
}
```

**Comment by LPTK** [comment]
These problems were resolved some time ago by making the quasiquotes always infer `Any` rather than `AnyRef` and making the Squid APIs refer to closed code as `Code[T,Any]` rather than `Code[T,{}] = Code[T,AnyRef]`, because `Any` is the true top of the typing lattice and so has some nicer properties.
